/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Windowutil (void);
GtkWidget* create_WindowAjout (void);
GtkWidget* create_windowmodifierr (void);
GtkWidget* create_windowetudd (void);
